# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='year',
            field=models.IntegerField(),
        ),
    ]
