# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0007_auto_20161202_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('yid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='maxtemp',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='temperature.Year'),
        ),
        migrations.AlterField(
            model_name='meantemp',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='temperature.Year'),
        ),
        migrations.AlterField(
            model_name='mintemp',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='temperature.Year'),
        ),
        migrations.AlterField(
            model_name='rainfall',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='temperature.Year'),
        ),
        migrations.AlterField(
            model_name='sunshine',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='temperature.Year'),
        ),
    ]
